---@meta

---@class Node
---@field parent Node|nil The node's parent
---@field name string The node's name
---@field class string The node's class
---@field c table For quickly accessing to child objects. `node.c.child.grandchild` is equivalent to `node:getChildren("child"):getChildren("grandchild")`
---@field inherit fun(self, class):Node For inheriting from this node
---@field new fun(self):Node Create a new Node
---@field lock fun(self):nil Lock this node permanently
---@field getFirstChild fun(self, name):Node Get first child of matching `name`
---@field getChildren fun(self):table,Node Get all children
---@field config fun(self, configs) Quickly configure the node